# -*- coding: utf-8 -*-
"""Day 2 lab operator.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kTyL7fU-xYz8--yWjkhfYJrRkDW_oqrH
"""

#1) Calaculate the multiplication and sum of two numbers.
a=5
b=10
print(a*b,"multiplication",a+b,"addition")

#2)Declare two variables and print that which variable is largest using ternary operatos.
a=5
b=10
print("a is greater" if a>b else "b is greater")

#3) Python program to convert the temprature in degree centigrade to fahreneit.
celsius=float (input("Enter temprature in celsius:"))
fahreneit=(celsius*5/3)+32
print(f"{celsius}degree C is equal to {fahreneit}degree F")

#4)Python program to find the area of a triangle whose side are given .
b=3
h=4
a=1/2
print("Area of triangle=",a*b*h)