# -*- coding: utf-8 -*-
"""Day 3 lab Conditional

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d_iB9O7D3Uai8yjFzA1yqQMgkBLtaAZa
"""

#1.	Using input() function take one number from the user and using ternary operators check whether the number is even or odd.
num = int(input("Enter a number: "))
print("Even" if num % 2 == 0 else "Odd")

#2)Using input function take two number and then swap the number.
a = int(input("Enter a number: "))
b = int(input("Enter a number: "))
a, b = b, a
print("a =", a)
print("b =", b)

#3)Write a Program to Convert Kilometers to Miles.
km = float(input("Enter distance in kilometers: "))
miles = km * 0.621371
print("Distance in miles:", miles)

#3.	Write a Program to Convert Kilometers to Miles.
km = float(input("Enter distance in kilometers: "))
miles = km * 0.621371
print("Distance in miles:", miles)

#4)Find the Simple Interest on Rs. 200 for 5 years at 5% per year.
p = 200
r = 10
t = 5
si = (p * r * t) / 100
print("Simple Interest:", si)