# -*- coding: utf-8 -*-
"""Day 4 lab control statement

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ucl09FlV89uM_Rt0qk4CfsByVHnzBj5k
"""

# 1) Python program to check leap year.
year = int(input("Ente a year :"))
if (year % 4== 0):
  if (year % 100 == 0):
    if (year % 400 == 0):
      print (f"{year} is a leap year.")
    else:
      print(f"{year} is not a leap year .")
  else:
    print(f"{year} is a leap year.")
else:
  print(f"{year} is not a laep year.")

#2)	Python Program to Find the Largest Among Three Numbers.
a = int(input("Enter first number : "))
b = int(input( "Enter second number :"))
c = int(input("Enter second number :"))
if a>=b and a>=c:
  print(f"{a} is the largest number.")
elif b>=a and b>=c:
  print(f"{b} is the largest number.")
else:
  print(f"{c} is the largest.")

#3)	Python Program to Check if a Number is Positive, Negative or 0.
num = int(input("enter a number:"))
if num>0:
  print("The number is positive.")
elif num < 0:
  print("The number is negative.")
else:
  print("The number is zero.")

#4) A toy vendor supplies three types of toys: Battery Based Toys, Key-based Toys, and Electrical Charging Based Toys. The vendor gives a discount of
#10% on orders for battery-based toys if the order is for more than Rs. 1000. On orders of more than Rs. 100 for key-based toys, a discount of 5% is given, and a discount of
#10% is given on orders for electrical charging based toys of value more than Rs. 500. Assume that the numeric codes 1,2 and 3 are used for battery based toys, key-based toys,
#and electrical charging based toys respectively. Write a program that reads the product code and the order amount and prints out the net amount that the customer is required to pay after the discount.
print("Product Codes:\n1: Battery Based Toy\n2: Key-Based Toy\n3: Electrical Charging Based Toy")
code = int(input("Enter product code (1/2/3): "))
amount = float(input("Enter order amount: "))

if code == 1:
    if amount > 1000:
        discount = 0.10 * amount
    else:
        discount = 0
elif code == 2:
    if amount > 100:
        discount = 0.05 * amount
    else:
        discount = 0
elif code == 3:
    if amount > 500:
        discount = 0.10 * amount
    else:
        discount = 0
else:
    print("Invalid product code.")
    discount = 0
    amount = 0

net_amount = amount - discount
print(f"Net amount to be paid: Rs. {net_amount:.2f}")

#5)
distance = int(input("Enter distance traveled (in km): "))

if 1 <= distance <= 50:
    fare = distance * 8
elif 51 <= distance <= 100:
    fare = distance * 10
else:
    fare = 0
    print("Distance out of range.")

if fare > 0:
    print(f"Total fare: Rs. {fare}")