# -*- coding: utf-8 -*-
"""Day_11 Lab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NVi8IXx3p3SHePK6rXvRrKbGXcpCTSpp
"""

#Q1) Write a Python program and calculate the mean of the below dictionary.
#test_dict("A": 6, "B": 9, "C": 5, "D": 7, "E":4)

test_dict = {"A": 6, "B": 9, "C": 5, "D": 7, "E": 4}
total = 0
count = 0
for key in test_dict:
    total += test_dict[key]
    count += 1
    mean = total / count
print(mean)

#Q2)Write a Python script to concatenate the following dictionaries to create a new one.

dic1 = {1: 10, 2: 20}
dic2 = {3: 30, 4: 40}
dic3 = {5: 50, 6: 60}
result = {}
for d in (dic1, dic2, dic3):
    for key in d:
        result[key] = d[key]
print("Concatenated Dictionary:", result)

#Q3)Write a Python program to get the key, value and item in a dictionary.
dict_num = {1: 10, 2: 20, 3: 30, 4: 40, 5: 50, 6: 60}
clean_dict = {}
for key in dict_num:
    if dict_num[key] != '' and dict_num[key] is not None:
        clean_dict[key] = dict_num[key]
print("Dictionary with empty items dropped:\n")
print(f"{'key':<10}{'value':<10}")
for key in clean_dict:
    print(f"{key:<10}{clean_dict[key]:<10}")

#Q4) Write a Python program to get the key, value and item in a dictionary.

input_dict = {1: 10, 2: 20, 3:None, 4: 40, 5: None, 6: 60}
clean_dict = {}
for key in input_dict:
    if input_dict[key] is not None:
        clean_dict[key] = input_dict[key]
print("Dictionary with Empty Items Dropped:")
print(clean_dict)