# -*- coding: utf-8 -*-
"""lab 4 loop

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1drCXBgS2gD2E9Bx9u3ckUuoxqoStvZj-
"""

print("Welcome to SimpleBite Online Food Ordering System 🍽")
print("--------------------------------------------------------")
print("Menu:")
print("1. Pizza       - Rs. 150")
print("2. Burger      - Rs. 80")
print("3. Sandwich    - Rs. 60")
print("4. French Fries- Rs. 50")
print("5. Soft Drink  - Rs. 40")

# Prices dictionary
prices = {
    1: 150,
    2: 80,
    3: 60,
    4: 50,
    5: 40
}

total = 0
order_more = 'yes'

while order_more.lower() == 'yes':
    choice = int(input("\nEnter the item number you want to order (1-5): "))
    quantity = int(input("Enter quantity: "))

    if choice in prices:
        item_total = prices[choice] * quantity
        total += item_total
        print(f"Added to cart. Item total = Rs. {item_total}")
    else:
        print("Invalid choice. Please select from 1 to 5.")

    order_more = input("Do you want to order more? (yes/no): ")

print("\n Thank you for your order!")
print(f"Your total bill is: Rs. {total}")
print("Your order will be delivered shortly!")